// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCieJZRn9xjCk2KR5dkTMflNQtqTFnnwhQ',
    appId: '1:1044985831799:web:1cd207749f7284733c4172',
    messagingSenderId: '1044985831799',
    projectId: 'zerocost-streamer',
    authDomain: 'zerocost-streamer.firebaseapp.com',
    databaseURL: 'https://zerocost-streamer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zerocost-streamer.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX1e9UUvrClUSbxIMFFqlmz3cus5rr4aQ',
    appId: '1:1044985831799:android:953c4de747c20f5d3c4172',
    messagingSenderId: '1044985831799',
    projectId: 'zerocost-streamer',
    databaseURL: 'https://zerocost-streamer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zerocost-streamer.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa8jxfckc5m1kIQVFO1Fx6EKIih8qAjw0',
    appId: '1:1044985831799:ios:c961882f035213623c4172',
    messagingSenderId: '1044985831799',
    projectId: 'zerocost-streamer',
    databaseURL: 'https://zerocost-streamer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zerocost-streamer.firebasestorage.app',
    iosBundleId: 'com.example.zeroCostStreamer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa8jxfckc5m1kIQVFO1Fx6EKIih8qAjw0',
    appId: '1:1044985831799:ios:c961882f035213623c4172',
    messagingSenderId: '1044985831799',
    projectId: 'zerocost-streamer',
    databaseURL: 'https://zerocost-streamer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zerocost-streamer.firebasestorage.app',
    iosBundleId: 'com.example.zeroCostStreamer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCieJZRn9xjCk2KR5dkTMflNQtqTFnnwhQ',
    appId: '1:1044985831799:web:9629ae9f619ceb393c4172',
    messagingSenderId: '1044985831799',
    projectId: 'zerocost-streamer',
    authDomain: 'zerocost-streamer.firebaseapp.com',
    databaseURL: 'https://zerocost-streamer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'zerocost-streamer.firebasestorage.app',
  );
}
